service: lambda-function-CECA

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

plugins:
  - serverless-offline

custom:
  allowedHeaders:
    - Accept
    - Content-Type
    - Content-Lenght

functions:
  get_car:
    handler: app.handler.get_car
    description: GET /lambda_function/cars/{car_plate}
    events:
      - http:
          path: /lambda_function/cars/{car_plate}
          method: get
          request:
            parameters:
              paths:
                car_plate: true
          cors:
            origin: '*'
            headers: ${self:custom.allowedHeaders}
 